import pg from "pg";
const { Pool } = pg;
const pool = new Pool({
  connectionString:
    "postgresql://versoair@localhost:5432/versoair_business_intelligence",
});

const businesses = [
  [
    "Agence Publicitaire Verso",
    191,
    "Full-service advertising and branding agency",
    "Plateau",
    "+225 27 20 10 15",
    "contact@agence-verso.ci",
    4.8,
    24,
  ],
  [
    "Imprimerie Côte d'Ivoire",
    197,
    "Professional printing and publishing services",
    "Marcory",
    "+225 27 20 22 88",
    "print@imprimerie-ci.ci",
    4.6,
    18,
  ],
  [
    "CloudTech Solutions",
    226,
    "Modern internet café with gaming stations",
    "Yopougon",
    "+225 27 21 45 67",
    "info@cloudtech.ci",
    4.7,
    32,
  ],
  [
    "DataCenter Africa Plus",
    226,
    "Enterprise cloud hosting and data center services",
    "Plateau",
    "+225 27 20 50 99",
    "sales@datacenter-africa.ci",
    4.9,
    45,
  ],
  [
    "Immobilier Premium CI",
    231,
    "High-end property sales and rental services",
    "Cocody",
    "+225 27 22 11 22",
    "ventes@immobilier-premium.ci",
    4.8,
    28,
  ],
  [
    "Promotions Immobilières Afrika",
    232,
    "Real estate development and construction projects",
    "Yamoussoukro",
    "+225 30 64 00 33",
    "projects@promotions-afrika.ci",
    4.7,
    22,
  ],
  [
    "Cabinet Audit & Conseil Ivoire",
    236,
    "Comprehensive audit and business consulting",
    "Plateau",
    "+225 27 20 33 44",
    "audit@cabinet-ivoire.ci",
    4.9,
    38,
  ],
  [
    "Expert-Comptable Côte d'Ivoire",
    237,
    "Professional accounting and tax services",
    "Plateau",
    "+225 27 20 77 88",
    "comptable@expert-ci.ci",
    4.8,
    31,
  ],
  [
    "Clinique Cardiologique Excellence",
    247,
    "Specialized cardiology clinic with modern equipment",
    "Cocody",
    "+225 27 22 99 11",
    "cardio@clinique-excellence.ci",
    4.9,
    52,
  ],
  [
    "Hôpital Général Abidjan",
    246,
    "Full-service general hospital with emergency",
    "Treichville",
    "+225 27 21 55 00",
    "urgences@hopital-abidjan.ci",
    4.8,
    67,
  ],
  [
    "Poissonnerie Atlantique",
    261,
    "Fresh seafood market with daily deliveries",
    "Port-Bouet",
    "+225 27 30 22 11",
    "poisson@atlantique.ci",
    4.7,
    26,
  ],
  [
    "Traiteur Goût d'Afrique",
    259,
    "Professional catering for events and functions",
    "Marcory",
    "+225 27 21 88 99",
    "events@gout-afrique.ci",
    4.8,
    42,
  ],
  [
    "Pharmacie Vétérinaire Afrik",
    265,
    "Veterinary medications and animal health products",
    "Yopougon",
    "+225 27 21 66 77",
    "vet@pharmacie-afrik.ci",
    4.6,
    19,
  ],
  [
    "Clinique Vétérinaire Santé Plus",
    264,
    "Full veterinary clinic with surgery and diagnostics",
    "Cocody",
    "+225 27 22 44 55",
    "vet@sante-plus.ci",
    4.7,
    29,
  ],
  [
    "Plomberie Technique Ivoire",
    270,
    "Professional plumbing and water installation",
    "Plateau",
    "+225 27 20 66 88",
    "plomb@technique-ivoire.ci",
    4.7,
    35,
  ],
  [
    "Vitrerie Décor Côte d'Ivoire",
    272,
    "Glass cutting and installation services",
    "Marcory",
    "+225 27 21 33 44",
    "vitres@decor-ci.ci",
    4.6,
    22,
  ],
  [
    "Meubles Design Afrique",
    275,
    "Contemporary furniture and home decoration",
    "Plateau",
    "+225 27 20 99 00",
    "info@meubles-design.ci",
    4.8,
    41,
  ],
  [
    "Galerie d'Art Contemporain",
    278,
    "Modern and contemporary art gallery",
    "Cocody",
    "+225 27 22 77 88",
    "info@galerie-art.ci",
    4.9,
    38,
  ],
  [
    "Tissus & Textiles Premium",
    282,
    "High-quality fabrics and textile materials",
    "Plateau",
    "+225 27 20 55 66",
    "ventes@tissus-premium.ci",
    4.7,
    27,
  ],
  [
    "Boutique Mode Élégance",
    284,
    "Designer clothing and fashion boutique",
    "Cocody",
    "+225 27 22 88 99",
    "fashion@elegance-mode.ci",
    4.8,
    44,
  ],
  [
    "Opérateur Télécom Panafrique",
    223,
    "Mobile and fixed line telecommunications",
    "Plateau",
    "+225 27 20 10 00",
    "service@telecom-panafrique.ci",
    4.8,
    89,
  ],
  [
    "Réseau VoIP Afrique Plus",
    287,
    "Business VoIP solutions and communication",
    "Plateau",
    "+225 27 20 44 55",
    "voip@afrique-plus.ci",
    4.7,
    33,
  ],
  [
    "Abattoir Moderne Côte d'Ivoire",
    291,
    "Modern meat processing and distribution",
    "Yamoussoukro",
    "+225 30 64 11 22",
    "production@abattoir-ivoire.ci",
    4.6,
    20,
  ],
  [
    "Agrochimie Solutions Afrique",
    292,
    "Agricultural chemicals and crop protection",
    "Bouaké",
    "+225 33 75 00 11",
    "ventes@agrochimie-afrique.ci",
    4.7,
    25,
  ],
  [
    "Ambassade Consulaire Services",
    255,
    "Diplomatic and consular services",
    "Plateau",
    "+225 27 20 00 00",
    "info@ambassade-ci.ci",
    4.5,
    15,
  ],
  [
    "Associations Civiles Côte d'Ivoire",
    256,
    "NGO and civic association support",
    "Cocody",
    "+225 27 22 55 66",
    "contact@associations-ci.ci",
    4.6,
    18,
  ],
  [
    "Confédération Patronale Côte d'Ivoire",
    295,
    "Employer confederation and business advocacy",
    "Plateau",
    "+225 27 20 22 33",
    "info@confederation-ci.ci",
    4.7,
    24,
  ],
  [
    "Ordre des Experts Comptables",
    296,
    "Professional accounting standards",
    "Plateau",
    "+225 27 20 11 22",
    "ordres@experts-comptables.ci",
    4.8,
    32,
  ],
  [
    "Salon Beauté Élégance Plus",
    299,
    "Full-service beauty and aesthetic salon",
    "Cocody",
    "+225 27 22 66 77",
    "beauty@elegance-plus.ci",
    4.8,
    55,
  ],
  [
    "Spa & Wellness Afrique",
    300,
    "Luxury spa and wellness center",
    "Plateau",
    "+225 27 20 88 99",
    "spa@wellness-afrique.ci",
    4.9,
    63,
  ],
  [
    "Agence de Recrutement Talent",
    303,
    "Executive and professional recruitment",
    "Plateau",
    "+225 27 20 77 00",
    "jobs@talent-recrute.ci",
    4.8,
    39,
  ],
  [
    "Centre de Formation Professionnelle",
    314,
    "Vocational training and professional development",
    "Yopougon",
    "+225 27 21 99 00",
    "formation@training-ci.ci",
    4.7,
    36,
  ],
  [
    "Centre Spirituel Multiconfessionnel",
    351,
    "Multi-faith spiritual center",
    "Cocody",
    "+225 27 22 11 22",
    "contact@spirituel-ci.ci",
    4.6,
    17,
  ],
  [
    "Moteurs Marins Afrique",
    352,
    "Marine engine sales and maintenance",
    "Port-Bouet",
    "+225 27 30 44 55",
    "marine@moteurs-afrique.ci",
    4.7,
    21,
  ],
];

async function seed() {
  try {
    await pool.query("DELETE FROM businesses WHERE id > 1");

    for (const [
      name,
      catId,
      desc,
      loc,
      phone,
      email,
      rating,
      reviews,
    ] of businesses) {
      await pool.query(
        "INSERT INTO businesses (name, category_id, description, location, phone, email, rating, reviews, is_active) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, true)",
        [name, catId, desc, loc, phone, email, rating, reviews],
      );
    }

    const res = await pool.query("SELECT COUNT(*) as cnt FROM businesses");
    console.log(`✅ Seeded ${res.rows[0].cnt} businesses successfully!`);
    process.exit(0);
  } catch (err) {
    console.error("❌ Error:", err.message);
    process.exit(1);
  }
}

seed();
