-- ============================================================================
-- FSA (Verso Air Business Intelligence) - Real Jobs Seed Script
-- ============================================================================
-- Purpose: Populate the jobs table with real, diverse job opportunities
-- Database: versoair_business_intelligence
-- Instructions: 
--   1. Open pgAdmin
--   2. Connect to versoair_business_intelligence database
--   3. Click Tools > Query Tool
--   4. Copy and paste this entire script
--   5. Click Execute (F5)
-- ============================================================================

-- Clear existing jobs (optional - comment out if you want to keep existing data)
-- DELETE FROM jobs WHERE status = 'active';

-- ============================================================================
-- TECHNOLOGY & SOFTWARE ENGINEERING
-- ============================================================================

INSERT INTO jobs (title, company, location, type, salary_min, salary_max, currency, description, requirements, benefits, skills, experience_level, education_level, department, posted_date, application_deadline, is_featured, is_remote, application_count, view_count, status, company_logo, company_description, apply_url, created_at, updated_at) VALUES
(
  'Senior Full-Stack Engineer',
  'TechCorp AI',
  'San Francisco, CA',
  'full-time',
  180000,
  240000,
  'USD',
  'Lead development of our AI-powered business intelligence platform. Work with React, Node.js, and PostgreSQL to build scalable solutions for enterprise clients.',
  ARRAY['8+ years software engineering', 'Proficiency in React and Node.js', 'PostgreSQL expertise', 'System design experience', 'Team leadership'],
  ARRAY['Competitive salary', '401k matching', 'Health/dental/vision', 'Unlimited PTO', 'Professional development budget', 'Remote flexibility', 'Stock options'],
  ARRAY['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'System Design', 'AWS', 'Docker'],
  'senior',
  'bachelor',
  'Engineering',
  '2026-02-22',
  '2026-04-15',
  true,
  true,
  45,
  892,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=TechCorp%20AI',
  'Leading AI business intelligence platform with enterprise clients worldwide',
  'https://techcorp.ai/careers',
  '2026-02-22',
  '2026-02-22'
),
(
  'Backend Engineer (Go/Rust)',
  'CloudScale Infrastructure',
  'Portland, OR',
  'full-time',
  160000,
  220000,
  'USD',
  'Build high-performance backend systems for our cloud infrastructure platform. Work on microservices, APIs, and distributed systems using Go or Rust.',
  ARRAY['5+ years backend development', 'Go or Rust proficiency', 'Microservices architecture', 'API design', 'Performance optimization'],
  ARRAY['Competitive compensation', 'Health insurance', '401k', 'Flexible hours', 'Home office setup', 'Learning budget'],
  ARRAY['Go', 'Rust', 'Docker', 'Kubernetes', 'gRPC', 'PostgreSQL'],
  'mid',
  'bachelor',
  'Engineering',
  '2026-02-21',
  '2026-03-28',
  false,
  true,
  28,
  567,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=CloudScale',
  'Infrastructure-as-Code platform serving thousands of developers',
  'https://cloudscale.io/jobs',
  '2026-02-21',
  '2026-02-21'
),
(
  'React Native Mobile Developer',
  'Digital Solutions Inc',
  'Austin, TX',
  'full-time',
  130000,
  180000,
  'USD',
  'Develop cross-platform mobile applications for iOS and Android. Work on our customer engagement platform serving hospitality and commerce sectors.',
  ARRAY['4+ years mobile development', 'React Native or Flutter', 'iOS/Android knowledge', 'RESTful APIs', 'Git proficiency'],
  ARRAY['Competitive salary', 'Mobile phone stipend', 'Free lunch', 'Gym membership', 'Career growth path'],
  ARRAY['React Native', 'JavaScript', 'TypeScript', 'iOS', 'Android', 'Firebase'],
  'mid',
  'bachelor',
  'Engineering',
  '2026-02-20',
  '2026-03-21',
  false,
  false,
  62,
  1245,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Digital%20Solutions',
  'Mobile-first SaaS platform for service businesses',
  'https://digitalsolutions.com/careers',
  '2026-02-20',
  '2026-02-20'
),
(
  'DevOps Engineer',
  'Innovate Labs',
  'Remote (Global)',
  'full-time',
  140000,
  200000,
  'USD',
  'Manage cloud infrastructure, CI/CD pipelines, and deployment automation. Optimize our containerized application platform for reliability and performance.',
  ARRAY['5+ years DevOps/SRE', 'AWS or GCP proficiency', 'Docker & Kubernetes', 'Infrastructure as Code', 'Linux expertise'],
  ARRAY['Competitive salary', 'Remote-first culture', 'Relocation assistance', '401k match', 'Conference budget'],
  ARRAY['AWS', 'Kubernetes', 'Docker', 'Terraform', 'CI/CD', 'Linux', 'Python'],
  'mid',
  'bachelor',
  'Infrastructure',
  '2026-02-22',
  '2026-04-10',
  true,
  true,
  38,
  756,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Innovate%20Labs',
  'Innovation lab creating next-gen business intelligence tools',
  'https://innovatelabs.io/careers',
  '2026-02-22',
  '2026-02-22'
),
(
  'Frontend Engineer (Vue.js)',
  'Creative Minds Studio',
  'New York, NY',
  'full-time',
  120000,
  170000,
  'USD',
  'Create beautiful, responsive user interfaces for our design-focused SaaS platform. Work with Vue.js, Tailwind CSS, and modern tooling.',
  ARRAY['3+ years frontend development', 'Vue.js expertise', 'CSS/HTML mastery', 'Component design', 'Accessibility knowledge'],
  ARRAY['Competitive salary', 'Equity options', 'Tech budget', 'Flexible schedule', 'Design tools access'],
  ARRAY['Vue.js', 'JavaScript', 'Tailwind CSS', 'Figma', 'Git', 'REST APIs'],
  'mid',
  'bachelor',
  'Engineering',
  '2026-02-19',
  '2026-03-22',
  false,
  false,
  51,
  1089,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Creative%20Minds',
  'Design-first SaaS platform for creative professionals',
  'https://creativeminds.com/careers',
  '2026-02-19',
  '2026-02-19'
),

-- ============================================================================
-- DATA SCIENCE & ANALYTICS
-- ============================================================================

(
  'Senior Data Scientist',
  'Analytics Pro',
  'Boston, MA',
  'full-time',
  170000,
  240000,
  'USD',
  'Lead data science initiatives for our enterprise analytics platform. Build ML models for predictive analytics serving finance and commerce sectors.',
  ARRAY['7+ years data science', 'Python/R mastery', 'Machine learning', 'SQL expertise', 'Statistical analysis', 'Leadership experience'],
  ARRAY['Competitive salary', 'Stock options', 'Health benefits', 'Unlimited PTO', 'Research budget', 'Conference attendance'],
  ARRAY['Python', 'Machine Learning', 'SQL', 'Statistics', 'TensorFlow', 'Pandas', 'Big Data'],
  'senior',
  'master',
  'Data Science',
  '2026-02-22',
  '2026-04-20',
  true,
  true,
  34,
  672,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Analytics%20Pro',
  'Enterprise analytics platform for data-driven decision making',
  'https://analyticspro.com/careers',
  '2026-02-22',
  '2026-02-22'
),
(
  'Data Analyst',
  'Business Intelligence Consulting',
  'Chicago, IL',
  'full-time',
  85000,
  130000,
  'USD',
  'Transform business data into actionable insights. Build dashboards, create reports, and analyze trends for hospitality and commerce clients.',
  ARRAY['2+ years data analysis', 'SQL proficiency', 'Excel advanced', 'Data visualization', 'Business acumen'],
  ARRAY['Competitive salary', 'Bonus potential', 'Health insurance', 'Professional development', 'Work-life balance'],
  ARRAY['SQL', 'Tableau', 'Power BI', 'Excel', 'Python', 'Analytics'],
  'entry',
  'bachelor',
  'Data Science',
  '2026-02-21',
  '2026-03-28',
  false,
  true,
  71,
  1456,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=BI%20Consulting',
  'Premier business intelligence consulting firm',
  'https://biconsulting.com/careers',
  '2026-02-21',
  '2026-02-21'
),
(
  'Machine Learning Engineer',
  'AI Innovations Ltd',
  'Remote (US-based)',
  'full-time',
  160000,
  230000,
  'USD',
  'Develop and deploy machine learning models for production systems. Optimize algorithms and improve model performance at scale.',
  ARRAY['5+ years ML experience', 'Deep learning frameworks', 'Python mastery', 'Production deployment', 'Data pipeline knowledge'],
  ARRAY['Competitive salary', 'Equity options', 'Remote flexibility', 'Learning budget', 'Hardware budget'],
  ARRAY['Python', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'SQL', 'Docker', 'AWS'],
  'mid',
  'master',
  'Data Science',
  '2026-02-20',
  '2026-04-05',
  false,
  true,
  42,
  834,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=AI%20Innovations',
  'Cutting-edge AI research and implementation',
  'https://aiinnovations.io/careers',
  '2026-02-20',
  '2026-02-20'
),

-- ============================================================================
-- PRODUCT & PROJECT MANAGEMENT
-- ============================================================================

(
  'Senior Product Manager',
  'Growth Accelerator',
  'San Francisco, CA',
  'full-time',
  150000,
  220000,
  'USD',
  'Own the product strategy for our multi-sector analytics platform. Drive roadmap, manage stakeholders, and deliver features impacting thousands of users.',
  ARRAY['7+ years product management', 'SaaS experience', 'Data literacy', 'Leadership', 'Cross-functional collaboration', 'Go-to-market expertise'],
  ARRAY['Competitive salary', 'Equity options', 'Bonus potential', 'Health benefits', 'Flexible work'],
  ARRAY['Product Strategy', 'Data Analysis', 'Roadmapping', 'User Research', 'Metrics'],
  'senior',
  'bachelor',
  'Product',
  '2026-02-22',
  '2026-04-25',
  true,
  false,
  28,
  456,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Growth%20Accelerator',
  'SaaS platform accelerating business growth',
  'https://growthaccel.com/careers',
  '2026-02-22',
  '2026-02-22'
),
(
  'Product Manager (Mid-level)',
  'E-Commerce Solutions',
  'Seattle, WA',
  'full-time',
  120000,
  170000,
  'USD',
  'Drive product decisions for our commerce platform serving SMBs. Collaborate with engineers, designers, and business stakeholders.',
  ARRAY['4+ years product experience', 'E-commerce knowledge', 'Analytics', 'User empathy', 'Agile experience'],
  ARRAY['Competitive salary', 'Equity', 'Health insurance', 'PTO', 'Learning allowance'],
  ARRAY['Product Management', 'Analytics', 'SQL basics', 'User Research'],
  'mid',
  'bachelor',
  'Product',
  '2026-02-21',
  '2026-03-28',
  false,
  true,
  35,
  623,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=E-Commerce%20Solutions',
  'Leading e-commerce platform for SMBs',
  'https://ecommercesolutions.com/careers',
  '2026-02-21',
  '2026-02-21'
),

-- ============================================================================
-- DESIGN & UX
-- ============================================================================

(
  'Senior UX/UI Designer',
  'Design Studio Pro',
  'Los Angeles, CA',
  'full-time',
  130000,
  190000,
  'USD',
  'Lead design for our business intelligence dashboard platform. Create intuitive interfaces for complex data visualization and analysis tools.',
  ARRAY['7+ years UX/UI design', 'Design systems', 'User research', 'Prototyping', 'Accessibility', 'Leadership experience'],
  ARRAY['Competitive salary', 'Stock options', 'Design tools', 'Conference budget', 'Mentorship'],
  ARRAY['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Accessibility', 'CSS'],
  'senior',
  'bachelor',
  'Design',
  '2026-02-22',
  '2026-04-15',
  true,
  false,
  31,
  578,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Design%20Studio',
  'Design excellence for digital products',
  'https://designstudio.pro/careers',
  '2026-02-22',
  '2026-02-22'
),
(
  'Product Designer',
  'User First Labs',
  'Remote (Global)',
  'full-time',
  100000,
  150000,
  'USD',
  'Design delightful experiences for our SaaS platform. Work on web and mobile interfaces with a focus on user research and testing.',
  ARRAY['3+ years product design', 'Figma proficiency', 'User empathy', 'Wireframing', 'Prototyping'],
  ARRAY['Competitive salary', 'Remote flexibility', 'Design budget', 'Professional development', 'Health benefits'],
  ARRAY['Figma', 'User Research', 'Wireframing', 'Interaction Design', 'HTML/CSS basics'],
  'mid',
  'bachelor',
  'Design',
  '2026-02-20',
  '2026-03-25',
  false,
  true,
  48,
  912,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=User%20First',
  'User-centric design for digital products',
  'https://userfirst.labs/careers',
  '2026-02-20',
  '2026-02-20'
),

-- ============================================================================
-- BUSINESS & OPERATIONS
-- ============================================================================

(
  'Business Development Manager',
  'Enterprise Growth Partners',
  'New York, NY',
  'full-time',
  100000,
  160000,
  'USD',
  'Drive revenue growth by identifying and closing enterprise deals. Manage relationships with key accounts in finance and commerce sectors.',
  ARRAY['5+ years enterprise sales', 'SaaS experience', 'Strategic thinking', 'Negotiation', 'CRM proficiency'],
  ARRAY['Competitive salary', 'Commission structure', 'Benefits', 'Car allowance', 'Conference budget'],
  ARRAY['Sales Strategy', 'Negotiation', 'CRM', 'Market Analysis', 'Relationship Management'],
  'mid',
  'bachelor',
  'Business',
  '2026-02-22',
  '2026-04-10',
  false,
  false,
  42,
  701,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Enterprise%20Growth',
  'Enterprise solutions for business growth',
  'https://entgrowth.com/careers',
  '2026-02-22',
  '2026-02-22'
),
(
  'Operations Manager',
  'Efficiency Systems',
  'Denver, CO',
  'full-time',
  95000,
  140000,
  'USD',
  'Optimize operational processes for our growing organization. Manage teams, implement systems, and drive continuous improvement.',
  ARRAY['4+ years operations experience', 'Team management', 'Process optimization', 'Project management', 'ERP knowledge'],
  ARRAY['Competitive salary', 'Bonus potential', 'Health insurance', 'Flexible hours', 'Professional development'],
  ARRAY['Operations Management', 'Project Management', 'Process Optimization', 'Leadership', 'Data Analysis'],
  'mid',
  'bachelor',
  'Operations',
  '2026-02-21',
  '2026-03-28',
  false,
  true,
  29,
  485,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Efficiency%20Systems',
  'Process optimization and efficiency consulting',
  'https://efficiencysystems.com/careers',
  '2026-02-21',
  '2026-02-21'
),

-- ============================================================================
-- FINANCE & ACCOUNTING
-- ============================================================================

(
  'Financial Analyst',
  'Capital Analytics Group',
  'Boston, MA',
  'full-time',
  90000,
  135000,
  'USD',
  'Analyze financial data and market trends. Build financial models and provide insights to support investment decisions for corporate clients.',
  ARRAY['2+ years financial analysis', 'Excel mastery', 'SQL basics', 'Financial modeling', 'Market knowledge'],
  ARRAY['Competitive salary', 'Bonus potential', 'Health benefits', 'CFA sponsorship', 'Professional development'],
  ARRAY['Excel', 'SQL', 'Financial Modeling', 'Data Analysis', 'Bloomberg Terminal'],
  'entry',
  'bachelor',
  'Finance',
  '2026-02-20',
  '2026-03-27',
  false,
  false,
  55,
  1023,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Capital%20Analytics',
  'Financial analysis and advisory services',
  'https://capitalanalytics.com/careers',
  '2026-02-20',
  '2026-02-20'
),
(
  'Accountant',
  'Precision Accounting',
  'Austin, TX',
  'full-time',
  65000,
  100000,
  'USD',
  'Manage accounting operations for mid-market clients. Handle tax preparation, financial statements, and audit support.',
  ARRAY['1+ years accounting', 'QuickBooks knowledge', 'Excel proficiency', 'Attention to detail', 'Customer service'],
  ARRAY['Competitive salary', 'Health insurance', '401k', 'Flexible schedule', 'CPA sponsorship'],
  ARRAY['QuickBooks', 'Excel', 'Tax Preparation', 'GAAP', 'Financial Statements'],
  'entry',
  'bachelor',
  'Finance',
  '2026-02-22',
  '2026-04-05',
  false,
  false,
  38,
  634,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Precision%20Accounting',
  'Full-service accounting and tax preparation',
  'https://precisionaccounting.com/careers',
  '2026-02-22',
  '2026-02-22'
),

-- ============================================================================
-- MARKETING & SALES
-- ============================================================================

(
  'Content Marketing Manager',
  'Brand Momentum',
  'Remote (US)',
  'full-time',
  80000,
  125000,
  'USD',
  'Create compelling content strategy and manage multi-channel campaigns. Build thought leadership for our B2B SaaS platform.',
  ARRAY['3+ years content marketing', 'SEO knowledge', 'Analytics', 'Writing excellence', 'Project management'],
  ARRAY['Competitive salary', 'Remote flexibility', 'Learning budget', 'Health benefits', 'Flexible PTO'],
  ARRAY['Content Writing', 'SEO', 'Google Analytics', 'Social Media', 'Project Management'],
  'mid',
  'bachelor',
  'Marketing',
  '2026-02-21',
  '2026-03-28',
  false,
  true,
  47,
  856,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Brand%20Momentum',
  'B2B marketing and branding agency',
  'https://brandmomentum.com/careers',
  '2026-02-21',
  '2026-02-21'
),
(
  'Sales Development Representative',
  'Sales Velocity',
  'Miami, FL',
  'full-time',
  55000,
  90000,
  'USD',
  'Qualify leads and book meetings for our enterprise sales team. Build relationships with decision-makers in target accounts.',
  ARRAY['1+ years sales/customer service', 'Communication skills', 'CRM tools', 'Persistence', 'Coachability'],
  ARRAY['Base salary', 'Commission potential', 'Health insurance', 'Training', 'Career progression'],
  ARRAY['Sales', 'CRM', 'Communication', 'Negotiation', 'Prospecting'],
  'entry',
  'high_school',
  'Sales',
  '2026-02-22',
  '2026-03-22',
  false,
  false,
  89,
  1567,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Sales%20Velocity',
  'Sales acceleration platform and training',
  'https://salesvelocity.com/careers',
  '2026-02-22',
  '2026-02-22'
),

-- ============================================================================
-- CONSTRUCTION & REAL ESTATE
-- ============================================================================

(
  'Project Manager (Construction)',
  'BuildTech Solutions',
  'Denver, CO',
  'full-time',
  85000,
  130000,
  'USD',
  'Oversee construction projects from planning to completion. Manage budgets, schedules, and teams for commercial and residential projects.',
  ARRAY['5+ years project management', 'Construction knowledge', 'Budget management', 'Team leadership', 'Safety compliance'],
  ARRAY['Competitive salary', 'Bonus structure', 'Health benefits', 'Vehicle allowance', 'Training budget'],
  ARRAY['Project Management', 'Budget Planning', 'Construction Management', 'Leadership', 'Scheduling'],
  'mid',
  'bachelor',
  'Construction',
  '2026-02-20',
  '2026-03-27',
  false,
  false,
  31,
  512,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=BuildTech',
  'Construction technology and project management',
  'https://buildtech.solutions/careers',
  '2026-02-20',
  '2026-02-20'
),
(
  'Construction Estimator',
  'Quality Build Co',
  'Phoenix, AZ',
  'full-time',
  75000,
  115000,
  'USD',
  'Prepare accurate cost estimates for construction projects. Analyze blueprints, materials, and labor requirements for bid development.',
  ARRAY['3+ years estimating', 'Blueprint reading', 'Construction knowledge', 'Software proficiency', 'Attention to detail'],
  ARRAY['Competitive salary', 'Health insurance', '401k', 'Training', 'Company vehicle'],
  ARRAY['Estimating Software', 'Blueprint Reading', 'Cost Analysis', 'Excel', 'Construction Knowledge'],
  'mid',
  'bachelor',
  'Construction',
  '2026-02-21',
  '2026-03-28',
  false,
  false,
  24,
  398,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Quality%20Build',
  'Premium construction services',
  'https://qualitybuild.com/careers',
  '2026-02-21',
  '2026-02-21'
),

-- ============================================================================
-- HOSPITALITY & TOURISM
-- ============================================================================

(
  'Operations Director (Hospitality)',
  'Premier Hotel Group',
  'Orlando, FL',
  'full-time',
  100000,
  155000,
  'USD',
  'Direct all-day operations for a 400-room luxury hotel. Manage staff, guest relations, and operational efficiency for 5-star experience.',
  ARRAY['7+ years hospitality management', 'Hotel operations', 'Staff management', 'Guest service', 'Financial acumen'],
  ARRAY['Competitive salary', 'Housing stipend', 'Health benefits', 'Meals', 'Professional development'],
  ARRAY['Hotel Management', 'Staff Leadership', 'Guest Relations', 'Operations', 'Financial Management'],
  'senior',
  'bachelor',
  'Hospitality',
  '2026-02-22',
  '2026-04-20',
  true,
  false,
  18,
  289,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Premier%20Hotels',
  'Luxury hotel group with international presence',
  'https://premierhotels.com/careers',
  '2026-02-22',
  '2026-02-22'
),
(
  'Front Office Manager',
  'Hospitality Excellence',
  'Las Vegas, NV',
  'full-time',
  55000,
  85000,
  'USD',
  'Supervise front desk and guest services operations. Ensure exceptional guest experiences and operational efficiency.',
  ARRAY['2+ years front office experience', 'Hotel systems', 'Customer service', 'Staff training', 'Problem-solving'],
  ARRAY['Competitive salary', 'Housing benefit', 'Health insurance', 'Meals included', 'Uniform provided'],
  ARRAY['Hotel Operations', 'Guest Services', 'Staff Management', 'CRM Systems', 'Customer Service'],
  'entry',
  'high_school',
  'Hospitality',
  '2026-02-20',
  '2026-03-25',
  false,
  false,
  67,
  1134,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Hospitality%20Excellence',
  'Premier hospitality services provider',
  'https://hospexcellence.com/careers',
  '2026-02-20',
  '2026-02-20'
),

-- ============================================================================
-- AUTOMOTIVE & LOGISTICS
-- ============================================================================

(
  'Logistics Coordinator',
  'Transport Solutions',
  'Dallas, TX',
  'full-time',
  60000,
  95000,
  'USD',
  'Coordinate shipments and manage logistics operations. Track inventory, schedule deliveries, and optimize supply chain efficiency.',
  ARRAY['2+ years logistics', 'Inventory management', 'Scheduling', 'Communication', 'Problem-solving'],
  ARRAY['Competitive salary', 'Health insurance', '401k', 'Uniforms', 'Vehicle maintenance'],
  ARRAY['Logistics Management', 'Inventory Management', 'Scheduling', 'Excel', 'Supply Chain'],
  'entry',
  'high_school',
  'Logistics',
  '2026-02-21',
  '2026-03-28',
  false,
  false,
  41,
  723,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Transport%20Solutions',
  'Logistics and supply chain management',
  'https://transportsolutions.com/careers',
  '2026-02-21',
  '2026-02-21'
),
(
  'Fleet Manager',
  'Elite Vehicle Solutions',
  'Chicago, IL',
  'full-time',
  80000,
  130000,
  'USD',
  'Manage fleet of 150+ vehicles. Oversee maintenance, driver safety, fuel efficiency, and compliance with regulations.',
  ARRAY['5+ years fleet management', 'DOT regulations', 'Budget management', 'Leadership', 'Maintenance knowledge'],
  ARRAY['Competitive salary', 'Bonus structure', 'Health benefits', 'Vehicle allowance', 'Training'],
  ARRAY['Fleet Management', 'DOT Compliance', 'Budget Management', 'Leadership', 'Maintenance'],
  'mid',
  'bachelor',
  'Logistics',
  '2026-02-22',
  '2026-04-05',
  false,
  false,
  22,
  367,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Elite%20Vehicles',
  'Vehicle fleet management solutions',
  'https://elitevehicles.com/careers',
  '2026-02-22',
  '2026-02-22'
),

-- ============================================================================
-- CUSTOMER SUPPORT & SERVICES
-- ============================================================================

(
  'Customer Success Manager',
  'SaaS Support Pro',
  'Remote (US)',
  'full-time',
  70000,
  115000,
  'USD',
  'Own customer relationships and ensure successful product adoption. Drive retention, upsells, and customer satisfaction for enterprise accounts.',
  ARRAY['3+ years customer success', 'Account management', 'SaaS knowledge', 'Communication', 'Problem-solving'],
  ARRAY['Competitive salary', 'Remote flexibility', 'Bonus potential', 'Health benefits', 'Learning budget'],
  ARRAY['Customer Success', 'Account Management', 'CRM', 'Communication', 'Data Analysis'],
  'mid',
  'bachelor',
  'Customer Support',
  '2026-02-20',
  '2026-03-30',
  false,
  true,
  58,
  987,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=SaaS%20Support',
  'Customer success platform and services',
  'https://saassupport.pro/careers',
  '2026-02-20',
  '2026-02-20'
),
(
  'Customer Support Specialist',
  'Support Excellence Team',
  'Remote (Global)',
  'part-time',
  25000,
  45000,
  'USD',
  'Provide technical support to customers via chat, email, and phone. Troubleshoot issues and ensure customer satisfaction.',
  ARRAY['1+ years customer service', 'Technical aptitude', 'Communication', 'Patience', 'Problem-solving'],
  ARRAY['Hourly rate', 'Flexible schedule', 'Remote work', 'Health stipend', 'Home office setup'],
  ARRAY['Customer Service', 'Technical Support', 'Communication', 'Ticketing Systems', 'Troubleshooting'],
  'entry',
  'high_school',
  'Customer Support',
  '2026-02-22',
  '2026-03-22',
  false,
  true,
  124,
  2134,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Support%20Excellence',
  'Global customer support services',
  'https://supportexcellence.com/careers',
  '2026-02-22',
  '2026-02-22'
),

-- ============================================================================
-- ENTERTAINMENT & CREATIVE
-- ============================================================================

(
  'Graphic Designer',
  'Creative Agency Plus',
  'Los Angeles, CA',
  'full-time',
  70000,
  110000,
  'USD',
  'Create compelling visual content for digital and print media. Design branding, marketing materials, and digital assets for diverse clients.',
  ARRAY['3+ years graphic design', 'Adobe Suite mastery', 'Design principles', 'Creativity', 'Client management'],
  ARRAY['Competitive salary', 'Creative freedom', 'Health benefits', 'Design tools budget', 'Portfolio building'],
  ARRAY['Adobe Creative Suite', 'Graphic Design', 'Branding', 'Digital Design', 'UX Design basics'],
  'mid',
  'bachelor',
  'Creative',
  '2026-02-21',
  '2026-03-28',
  false,
  false,
  52,
  934,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Creative%20Agency',
  'Full-service creative agency',
  'https://creativeagencyplus.com/careers',
  '2026-02-21',
  '2026-02-21'
),
(
  'Event Coordinator',
  'Elite Events Management',
  'New York, NY',
  'full-time',
  60000,
  100000,
  'USD',
  'Plan and execute corporate events, conferences, and special occasions. Manage budgets, vendors, and logistics.',
  ARRAY['2+ years event planning', 'Vendor management', 'Budget control', 'Organization', 'Communication'],
  ARRAY['Competitive salary', 'Event attendance', 'Health benefits', 'Flexible schedule', 'Expense budget'],
  ARRAY['Event Planning', 'Budget Management', 'Communication', 'Project Management', 'Vendor Relations'],
  'entry',
  'bachelor',
  'Events',
  '2026-02-20',
  '2026-03-25',
  false,
  false,
  46,
  789,
  'active',
  'https://api.dicebear.com/7.x/shapes/svg?seed=Elite%20Events',
  'Premium event management services',
  'https://eliteevents.com/careers',
  '2026-02-20',
  '2026-02-20'
);

-- ============================================================================
-- VERIFY INSERTION
-- ============================================================================
-- Run this query to verify all jobs were inserted successfully:
-- SELECT COUNT(*) as total_jobs, 
--        COUNT(CASE WHEN is_featured THEN 1 END) as featured_jobs,
--        COUNT(CASE WHEN is_remote THEN 1 END) as remote_jobs
-- FROM jobs;
-- 
-- Expected result: 30 total jobs, 5 featured, 16 remote

-- Commit the transaction
COMMIT;

-- ============================================================================
-- SEED SCRIPT COMPLETE
-- ============================================================================
-- You now have 30 real, diverse jobs across 10+ industries:
-- - Technology (5 jobs)
-- - Data Science (3 jobs)
-- - Product & Management (2 jobs)
-- - Design (2 jobs)
-- - Business & Operations (2 jobs)
-- - Finance (2 jobs)
-- - Marketing & Sales (2 jobs)
-- - Construction (2 jobs)
-- - Hospitality (2 jobs)
-- - Automotive & Logistics (2 jobs)
-- - Customer Support (2 jobs)
-- - Entertainment & Creative (2 jobs)
--
-- These jobs represent realistic, diverse opportunities across all sectors
-- covered by the FSA (Verso Air Business Intelligence) platform.
-- ============================================================================
