/**
 * Country metadata for dynamic content localization.
 * Used across the home page and anywhere that needs
 * country-aware display text.
 */

export interface CountryMeta {
  name: string;
  demonym: string; // "Canadian", "Ivorian", "French"
  currency: string; // "CAD", "XOF", "EUR"
  currencySymbol: string; // "$", "CFA", "€"
  flag: string;
  phone: string; // example phone for contact display
  tld: string; // ".ca", ".ci", ".fr"
}

const META: Record<string, CountryMeta> = {
  // Americas
  US: {
    name: "United States",
    demonym: "American",
    currency: "USD",
    currencySymbol: "$",
    flag: "🇺🇸",
    phone: "+1 202 555 0100",
    tld: ".us",
  },
  CA: {
    name: "Canada",
    demonym: "Canadian",
    currency: "CAD",
    currencySymbol: "C$",
    flag: "🇨🇦",
    phone: "+1 613 555 0100",
    tld: ".ca",
  },
  MX: {
    name: "Mexico",
    demonym: "Mexican",
    currency: "MXN",
    currencySymbol: "$",
    flag: "🇲🇽",
    phone: "+52 55 1234 5678",
    tld: ".mx",
  },
  BR: {
    name: "Brazil",
    demonym: "Brazilian",
    currency: "BRL",
    currencySymbol: "R$",
    flag: "🇧🇷",
    phone: "+55 11 1234 5678",
    tld: ".br",
  },
  HT: {
    name: "Haïti",
    demonym: "Haitian",
    currency: "HTG",
    currencySymbol: "G",
    flag: "🇭🇹",
    phone: "+509 22 12 3456",
    tld: ".ht",
  },
  // Europe
  FR: {
    name: "France",
    demonym: "French",
    currency: "EUR",
    currencySymbol: "€",
    flag: "🇫🇷",
    phone: "+33 1 23 45 67 89",
    tld: ".fr",
  },
  DE: {
    name: "Germany",
    demonym: "German",
    currency: "EUR",
    currencySymbol: "€",
    flag: "🇩🇪",
    phone: "+49 30 123456",
    tld: ".de",
  },
  GB: {
    name: "United Kingdom",
    demonym: "British",
    currency: "GBP",
    currencySymbol: "£",
    flag: "🇬🇧",
    phone: "+44 20 7946 0958",
    tld: ".uk",
  },
  BE: {
    name: "Belgium",
    demonym: "Belgian",
    currency: "EUR",
    currencySymbol: "€",
    flag: "🇧🇪",
    phone: "+32 2 123 4567",
    tld: ".be",
  },
  CH: {
    name: "Switzerland",
    demonym: "Swiss",
    currency: "CHF",
    currencySymbol: "CHF",
    flag: "🇨🇭",
    phone: "+41 44 123 4567",
    tld: ".ch",
  },
  ES: {
    name: "Spain",
    demonym: "Spanish",
    currency: "EUR",
    currencySymbol: "€",
    flag: "🇪🇸",
    phone: "+34 91 123 4567",
    tld: ".es",
  },
  IT: {
    name: "Italy",
    demonym: "Italian",
    currency: "EUR",
    currencySymbol: "€",
    flag: "🇮🇹",
    phone: "+39 06 1234 5678",
    tld: ".it",
  },
  PT: {
    name: "Portugal",
    demonym: "Portuguese",
    currency: "EUR",
    currencySymbol: "€",
    flag: "🇵🇹",
    phone: "+351 21 123 4567",
    tld: ".pt",
  },
  // Africa
  CI: {
    name: "Côte d'Ivoire",
    demonym: "Ivorian",
    currency: "XOF",
    currencySymbol: "CFA",
    flag: "🇨🇮",
    phone: "+225 27 20 21 22 23",
    tld: ".ci",
  },
  SN: {
    name: "Sénégal",
    demonym: "Senegalese",
    currency: "XOF",
    currencySymbol: "CFA",
    flag: "🇸🇳",
    phone: "+221 33 123 4567",
    tld: ".sn",
  },
  CM: {
    name: "Cameroun",
    demonym: "Cameroonian",
    currency: "XAF",
    currencySymbol: "FCFA",
    flag: "🇨🇲",
    phone: "+237 2 22 12 34 56",
    tld: ".cm",
  },
  ML: {
    name: "Mali",
    demonym: "Malian",
    currency: "XOF",
    currencySymbol: "CFA",
    flag: "🇲🇱",
    phone: "+223 20 12 34 56",
    tld: ".ml",
  },
  BF: {
    name: "Burkina Faso",
    demonym: "Burkinabé",
    currency: "XOF",
    currencySymbol: "CFA",
    flag: "🇧🇫",
    phone: "+226 25 30 12 34",
    tld: ".bf",
  },
  GN: {
    name: "Guinée",
    demonym: "Guinean",
    currency: "GNF",
    currencySymbol: "FG",
    flag: "🇬🇳",
    phone: "+224 30 12 34 56",
    tld: ".gn",
  },
  TG: {
    name: "Togo",
    demonym: "Togolese",
    currency: "XOF",
    currencySymbol: "CFA",
    flag: "🇹🇬",
    phone: "+228 22 12 34 56",
    tld: ".tg",
  },
  BJ: {
    name: "Bénin",
    demonym: "Beninese",
    currency: "XOF",
    currencySymbol: "CFA",
    flag: "🇧🇯",
    phone: "+229 21 12 34 56",
    tld: ".bj",
  },
  NE: {
    name: "Niger",
    demonym: "Nigerien",
    currency: "XOF",
    currencySymbol: "CFA",
    flag: "🇳🇪",
    phone: "+227 20 12 34 56",
    tld: ".ne",
  },
  MG: {
    name: "Madagascar",
    demonym: "Malagasy",
    currency: "MGA",
    currencySymbol: "Ar",
    flag: "🇲🇬",
    phone: "+261 20 12 345 67",
    tld: ".mg",
  },
  CD: {
    name: "Congo (RDC)",
    demonym: "Congolese",
    currency: "CDF",
    currencySymbol: "FC",
    flag: "🇨🇩",
    phone: "+243 81 234 5678",
    tld: ".cd",
  },
  CG: {
    name: "Congo (Brazzaville)",
    demonym: "Congolese",
    currency: "XAF",
    currencySymbol: "FCFA",
    flag: "🇨🇬",
    phone: "+242 06 123 4567",
    tld: ".cg",
  },
  GA: {
    name: "Gabon",
    demonym: "Gabonese",
    currency: "XAF",
    currencySymbol: "FCFA",
    flag: "🇬🇦",
    phone: "+241 01 12 34 56",
    tld: ".ga",
  },
  MA: {
    name: "Maroc",
    demonym: "Moroccan",
    currency: "MAD",
    currencySymbol: "MAD",
    flag: "🇲🇦",
    phone: "+212 5 22 12 34 56",
    tld: ".ma",
  },
  DZ: {
    name: "Algérie",
    demonym: "Algerian",
    currency: "DZD",
    currencySymbol: "DA",
    flag: "🇩🇿",
    phone: "+213 21 12 34 56",
    tld: ".dz",
  },
  TN: {
    name: "Tunisie",
    demonym: "Tunisian",
    currency: "TND",
    currencySymbol: "DT",
    flag: "🇹🇳",
    phone: "+216 71 12 34 56",
    tld: ".tn",
  },
  ZA: {
    name: "South Africa",
    demonym: "South African",
    currency: "ZAR",
    currencySymbol: "R",
    flag: "🇿🇦",
    phone: "+27 11 123 4567",
    tld: ".za",
  },
  NG: {
    name: "Nigeria",
    demonym: "Nigerian",
    currency: "NGN",
    currencySymbol: "₦",
    flag: "🇳🇬",
    phone: "+234 1 234 5678",
    tld: ".ng",
  },
  // Asia / Middle East
  JP: {
    name: "Japan",
    demonym: "Japanese",
    currency: "JPY",
    currencySymbol: "¥",
    flag: "🇯🇵",
    phone: "+81 3 1234 5678",
    tld: ".jp",
  },
  CN: {
    name: "China",
    demonym: "Chinese",
    currency: "CNY",
    currencySymbol: "¥",
    flag: "🇨🇳",
    phone: "+86 10 1234 5678",
    tld: ".cn",
  },
  IN: {
    name: "India",
    demonym: "Indian",
    currency: "INR",
    currencySymbol: "₹",
    flag: "🇮🇳",
    phone: "+91 11 1234 5678",
    tld: ".in",
  },
  AE: {
    name: "United Arab Emirates",
    demonym: "Emirati",
    currency: "AED",
    currencySymbol: "AED",
    flag: "🇦🇪",
    phone: "+971 2 123 4567",
    tld: ".ae",
  },
};

const FALLBACK: CountryMeta = {
  name: "Global",
  demonym: "Global",
  currency: "USD",
  currencySymbol: "$",
  flag: "🌍",
  phone: "+1 000 000 0000",
  tld: ".com",
};

/** Get metadata for a country code. Falls back to a generic "Global" entry. */
export function getCountryMeta(code: string): CountryMeta {
  return META[code?.toUpperCase()] ?? FALLBACK;
}

/** All known country codes */
export const COUNTRY_CODES = Object.keys(META);
