import { db } from "../db";
import { properties } from "@shared/schema";
import dotenv from "dotenv";

dotenv.config();

const ivoryCoastProperties = [
  // ABIDJAN HOTELS
  {
    name: "Hotel Ivoire",
    description:
      "Luxury 5-star hotel overlooking the Ébrié Lagoon with world-class amenities and stunning views",
    type: "hotel",
    category: "luxury",
    location: "Cocody, Abidjan",
    city: "Abidjan",
    address: "Boulevard de la Corniche, Abidjan",
    latitude: "6.8276",
    longitude: "-5.3369",
    image: "https://images.unsplash.com/photo-1566182007330-55c764412db0?w=500",
    images: [
      "https://images.unsplash.com/photo-1566182007330-55c764412db0?w=500",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=500",
    ],
    price: "450",
    rating: "4.8",
    reviews: 234,
    bedrooms: 312,
    bathrooms: 320,
    area: 45000,
    guests: 624,
    amenities: ["wifi", "pool", "spa", "restaurant", "bar", "parking", "ac"],
    verified: true,
    instantBook: true,
    freeCancellation: true,
    discount: 0,
    featured: true,
    tags: ["luxury", "lagoon-view", "5-star"],
    hostName: "Hotel Ivoire Management",
    hostPhone: "+225 21 48 00 00",
    hostEmail: "info@hotelivoire.ci",
    superhost: true,
    responseRate: 100,
    responseTime: "< 30 minutes",
  },
  {
    name: "Radisson Blu Abidjan",
    description:
      "Modern business hotel with contemporary design in the heart of Abidjan's business district",
    type: "hotel",
    category: "luxury",
    location: "Plateau, Abidjan",
    city: "Abidjan",
    address: "Avenue Général de Gaulle, Plateau",
    latitude: "6.8252",
    longitude: "-5.5497",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500",
    images: [
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500",
      "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=500",
    ],
    price: "380",
    rating: "4.7",
    reviews: 189,
    bedrooms: 188,
    bathrooms: 188,
    area: 28000,
    guests: 376,
    amenities: [
      "wifi",
      "pool",
      "gym",
      "restaurant",
      "business-center",
      "parking",
      "ac",
    ],
    verified: true,
    instantBook: true,
    freeCancellation: false,
    discount: 5,
    featured: true,
    tags: ["business", "modern", "4-star"],
    hostName: "Radisson Blu Group",
    hostPhone: "+225 20 34 34 34",
    hostEmail: "abidjan@radissonblu.com",
    superhost: true,
    responseRate: 100,
    responseTime: "< 1 hour",
  },
  {
    name: "Novotel Abidjan",
    description:
      "Contemporary 4-star hotel featuring modern amenities and excellent service",
    type: "hotel",
    category: "standard",
    location: "Cocody, Abidjan",
    city: "Abidjan",
    address: "Rue du Docteur Crozet, Cocody",
    latitude: "6.8289",
    longitude: "-5.3248",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=500",
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=500",
      "https://images.unsplash.com/photo-1559773132-cb3aea458c5e?w=500",
    ],
    price: "280",
    rating: "4.5",
    reviews: 156,
    bedrooms: 127,
    bathrooms: 130,
    area: 18000,
    guests: 254,
    amenities: ["wifi", "pool", "gym", "restaurant", "parking", "ac"],
    verified: true,
    instantBook: true,
    freeCancellation: true,
    discount: 10,
    featured: false,
    tags: ["4-star", "modern", "comfortable"],
    hostName: "Novotel International",
    hostPhone: "+225 22 40 44 44",
    hostEmail: "novotel.abidjan@accor.com",
    superhost: true,
    responseRate: 98,
    responseTime: "1-2 hours",
  },
  {
    name: "Sofitel Abidjan",
    description:
      "Elegant luxury resort with beachfront access and premium dining experiences",
    type: "resort",
    category: "luxury",
    location: "Bingerville, Abidjan",
    city: "Abidjan",
    address: "Boulevard du Bingerville",
    latitude: "6.8156",
    longitude: "-5.3547",
    image: "https://images.unsplash.com/photo-1570129477492-45ea003588af?w=500",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45ea003588af?w=500",
      "https://images.unsplash.com/photo-1566186556519-40dd282ba0b8?w=500",
    ],
    price: "520",
    rating: "4.9",
    reviews: 312,
    bedrooms: 257,
    bathrooms: 270,
    area: 38000,
    guests: 514,
    amenities: [
      "wifi",
      "beach",
      "pool",
      "spa",
      "restaurant",
      "bar",
      "gym",
      "ac",
    ],
    verified: true,
    instantBook: true,
    freeCancellation: true,
    discount: 0,
    featured: true,
    tags: ["luxury", "beachfront", "resort"],
    hostName: "Sofitel Hotels Group",
    hostPhone: "+225 22 50 50 50",
    hostEmail: "sofitel.abidjan@sofitel.com",
    superhost: true,
    responseRate: 100,
    responseTime: "< 30 minutes",
  },

  // YAMOUSSOUKRO
  {
    name: "Hotel President",
    description:
      "Presidential hotel in the heart of Yamoussoukro with excellent facilities",
    type: "hotel",
    category: "luxury",
    location: "Centre Ville, Yamoussoukro",
    city: "Yamoussoukro",
    address: "Avenue Houphouët-Boigny",
    latitude: "6.8189",
    longitude: "-5.5514",
    image: "https://images.unsplash.com/photo-1512453050685-84aa27be0df5?w=500",
    images: [
      "https://images.unsplash.com/photo-1512453050685-84aa27be0df5?w=500",
      "https://images.unsplash.com/photo-1542314503-37143f4f4d2c?w=500",
    ],
    price: "320",
    rating: "4.6",
    reviews: 145,
    bedrooms: 156,
    bathrooms: 160,
    area: 22000,
    guests: 312,
    amenities: [
      "wifi",
      "pool",
      "restaurant",
      "bar",
      "parking",
      "ac",
      "conference-room",
    ],
    verified: true,
    instantBook: true,
    freeCancellation: false,
    discount: 8,
    featured: false,
    tags: ["presidential", "business", "4-star"],
    hostName: "Hotel President Management",
    hostPhone: "+225 30 64 64 64",
    hostEmail: "contact@hotelpresident.ci",
    superhost: true,
    responseRate: 95,
    responseTime: "1-2 hours",
  },

  // BOUAKE
  {
    name: "Hotel Independence",
    description:
      "Mid-range hotel offering comfortable rooms and reliable service in Bouaké",
    type: "hotel",
    category: "standard",
    location: "Centre Ville, Bouaké",
    city: "Bouaké",
    address: "Avenue Nationale",
    latitude: "7.6938",
    longitude: "-5.0301",
    image: "https://images.unsplash.com/photo-1535599810169-65b7d64286ae?w=500",
    images: [
      "https://images.unsplash.com/photo-1535599810169-65b7d64286ae?w=500",
      "https://images.unsplash.com/photo-1559599810-46d1c52494ee?w=500",
    ],
    price: "140",
    rating: "4.2",
    reviews: 87,
    bedrooms: 78,
    bathrooms: 80,
    area: 9500,
    guests: 156,
    amenities: ["wifi", "restaurant", "parking", "ac"],
    verified: false,
    instantBook: false,
    freeCancellation: true,
    discount: 15,
    featured: false,
    tags: ["budget-friendly", "convenient", "3-star"],
    hostName: "Hotel Independence",
    hostPhone: "+225 31 33 33 33",
    hostEmail: "contact@hotelindependence.ci",
    superhost: false,
    responseRate: 85,
    responseTime: "2-4 hours",
  },

  // DALOA
  {
    name: "Hotel Commerce",
    description:
      "Traditional hotel in Daloa offering basic but clean accommodation",
    type: "hotel",
    category: "budget",
    location: "Centre Ville, Daloa",
    city: "Daloa",
    address: "Route de Yamoussoukro",
    latitude: "6.8791",
    longitude: "-6.4527",
    image: "https://images.unsplash.com/photo-1515877152779-7d8083f3d55f?w=500",
    images: [
      "https://images.unsplash.com/photo-1515877152779-7d8083f3d55f?w=500",
    ],
    price: "85",
    rating: "3.8",
    reviews: 52,
    bedrooms: 48,
    bathrooms: 50,
    area: 5500,
    guests: 96,
    amenities: ["wifi", "parking", "ac"],
    verified: false,
    instantBook: true,
    freeCancellation: true,
    discount: 20,
    featured: false,
    tags: ["budget", "basic", "2-star"],
    hostName: "Hotel Commerce Owner",
    hostPhone: "+225 32 43 43 43",
    hostEmail: "contact@hotelcommerce.ci",
    superhost: false,
    responseRate: 75,
    responseTime: "4+ hours",
  },

  // SAN-PEDRO
  {
    name: "Beach Resort San-Pedro",
    description:
      "Beachfront resort with great ocean views and water sports facilities",
    type: "resort",
    category: "standard",
    location: "Beachfront, San-Pédro",
    city: "San-Pédro",
    address: "Boulevard de la Plage",
    latitude: "4.7471",
    longitude: "-6.6344",
    image: "https://images.unsplash.com/photo-1561047557-343bda6a00bb?w=500",
    images: [
      "https://images.unsplash.com/photo-1561047557-343bda6a00bb?w=500",
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500",
    ],
    price: "220",
    rating: "4.4",
    reviews: 113,
    bedrooms: 94,
    bathrooms: 100,
    area: 14000,
    guests: 188,
    amenities: [
      "wifi",
      "beach",
      "pool",
      "water-sports",
      "restaurant",
      "bar",
      "ac",
    ],
    verified: true,
    instantBook: true,
    freeCancellation: true,
    discount: 5,
    featured: false,
    tags: ["beach", "resort", "water-sports"],
    hostName: "San-Pedro Beach Resorts",
    hostPhone: "+225 34 74 74 74",
    hostEmail: "contact@sanpedoresort.ci",
    superhost: true,
    responseRate: 96,
    responseTime: "1-2 hours",
  },

  // GUESTHOUSES & APARTMENTS
  {
    name: "Cocody Guest House",
    description:
      "Cozy guesthouse in the residential Cocody area with home-like atmosphere",
    type: "guesthouse",
    category: "budget",
    location: "Cocody, Abidjan",
    city: "Abidjan",
    address: "Rue de la Paix, Cocody",
    latitude: "6.8345",
    longitude: "-5.3145",
    image: "https://images.unsplash.com/photo-1555195019-6b87da09a028?w=500",
    images: ["https://images.unsplash.com/photo-1555195019-6b87da09a028?w=500"],
    price: "95",
    rating: "4.3",
    reviews: 68,
    bedrooms: 6,
    bathrooms: 6,
    area: 800,
    guests: 12,
    amenities: ["wifi", "parking", "ac", "kitchen"],
    verified: true,
    instantBook: true,
    freeCancellation: true,
    discount: 10,
    featured: false,
    tags: ["guesthouse", "budget", "local"],
    hostName: "Marie Koffi",
    hostPhone: "+225 77 12 34 56",
    hostEmail: "marie@cocodyguest.ci",
    superhost: true,
    responseRate: 100,
    responseTime: "< 2 hours",
  },
  {
    name: "Plateau Apartment Suite",
    description:
      "Modern apartment in Plateau district with kitchen and laundry facilities",
    type: "apartment",
    category: "standard",
    location: "Plateau, Abidjan",
    city: "Abidjan",
    address: "Rue de la Liberté, Plateau",
    latitude: "6.8241",
    longitude: "-5.5498",
    image: "https://images.unsplash.com/photo-1543968519-d2eb44dc6bfa?w=500",
    images: [
      "https://images.unsplash.com/photo-1543968519-d2eb44dc6bfa?w=500",
      "https://images.unsplash.com/photo-1501643555353-4b95493f6730?w=500",
    ],
    price: "165",
    rating: "4.5",
    reviews: 92,
    bedrooms: 2,
    bathrooms: 1,
    area: 1200,
    guests: 4,
    amenities: ["wifi", "parking", "ac", "kitchen", "washer"],
    verified: true,
    instantBook: true,
    freeCancellation: false,
    discount: 0,
    featured: false,
    tags: ["apartment", "family", "full-equipped"],
    hostName: "Jean Pierre Sissoko",
    hostPhone: "+225 77 98 76 54",
    hostEmail: "jean@plateauapartment.ci",
    superhost: true,
    responseRate: 99,
    responseTime: "< 1 hour",
  },
];

async function seedProperties() {
  try {
    console.log("🌱 Starting property seed for Ivory Coast...");

    // Clear existing properties (optional - comment out if you want to keep existing data)
    // await db.delete(properties);
    // console.log("🗑️  Cleared existing properties");

    // Insert new properties
    for (const prop of ivoryCoastProperties) {
      await db.insert(properties).values({
        name: prop.name,
        description: prop.description,
        type: prop.type,
        category: prop.category,
        location: prop.location,
        city: prop.city,
        address: prop.address,
        latitude: prop.latitude,
        longitude: prop.longitude,
        image: prop.image,
        images: prop.images,
        price: prop.price,
        rating: prop.rating,
        reviews: prop.reviews,
        bedrooms: prop.bedrooms,
        bathrooms: prop.bathrooms,
        area: prop.area,
        guests: prop.guests,
        amenities: prop.amenities,
        verified: prop.verified,
        instantBook: prop.instantBook,
        freeCancellation: prop.freeCancellation,
        discount: prop.discount,
        featured: prop.featured,
        tags: prop.tags,
        hostName: prop.hostName,
        hostPhone: prop.hostPhone,
        hostEmail: prop.hostEmail,
        superhost: prop.superhost,
        responseRate: prop.responseRate,
        responseTime: prop.responseTime,
      });
    }

    console.log(
      `✅ Successfully seeded ${ivoryCoastProperties.length} properties from Ivory Coast!`,
    );

    // Show summary
    const summary = {
      luxury: ivoryCoastProperties.filter((p) => p.category === "luxury")
        .length,
      standard: ivoryCoastProperties.filter((p) => p.category === "standard")
        .length,
      budget: ivoryCoastProperties.filter((p) => p.category === "budget")
        .length,
      cities: [...new Set(ivoryCoastProperties.map((p) => p.city))],
    };

    console.log("📊 Seed Summary:", summary);

    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding properties:", error);
    process.exit(1);
  }
}

seedProperties();
